import Head from 'next/head';
import Image from 'next/image';
import {
  DashboardLayout,
  Header,
  LineGraph,
  RevenueCard,
  TableBody,
  TableHead,
} from '../components';
import { revenueData, tabledata } from '../helpers/dummy';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Dashboard - Clafiya</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <DashboardLayout>
        <Header />
        <section>
          <div
            className="flex sm:flex-wrap justify-between mt-[32px] no-scrollbar  w-full 
           items-center overflow-x-scroll  text-secondary  "
          >
            {revenueData.map((item) => (
              <RevenueCard
                key={item.id}
                title={item.title}
                amount={item.amount}
                icon={item.icon}
                color={item.color}
              />
            ))}
          </div>
          <div className="flex justify-between sm:flex-col items-start mt-[40px]">
            <div className="w-[49%] sm:w-full sm:mb-6  bg-[white] rounded-[8px] p-[24px] sm:p-[12px]">
              <div className="flex w-full justify-between items-center mb-4 ">
                <p className="text-[20px] font-bold">$ 112,174</p>
                <p className="text-grey text-[12px]">Income in current month</p>
              </div>
              <LineGraph color={'#336CFB'} />
            </div>
            <div className="w-[49%] sm:w-full  bg-[white] rounded-[8px] p-[24px] sm:p-[12px]">
              <div className="flex w-full justify-between items-center mb-4 ">
                <p className="text-[20px] font-bold">5,210</p>
                <p className="text-grey text-[12px]">
                  Total Number of Appointment
                </p>
              </div>
              <LineGraph color={'orange'} />
            </div>
          </div>
          <div
            className=" w-full mt-[40px]  bg-[white] mb-[100px] 
          py-[24px] rounded-[8px] shadow-[0px_12px_26px_rgba(16,_30,_115,_0.06)]"
          >
            <p className="text-[20px] px-[24px] mb-[16px] font-bold text-secondary">
              Appointment Activity
            </p>
            <div className="w-full overflow-x-scroll  ">
              <TableHead />
              {tabledata.map((item) => {
                return (
                  <TableBody
                    key={item.id}
                    image={item.image}
                    name={item.name}
                    email={item.email}
                    date={item.date}
                    timeVisited={item.visited}
                    chw={item.chw}
                    plan={item.plan}
                  />
                );
              })}
            </div>
          </div>
        </section>
      </DashboardLayout>
    </div>
  );
}
